spring:
  application:
    name: saas-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/saas_backend
    username: postgres
    password: ${DB_PASSWORD}

  flyway:
    locations: classpath:db/migration/public

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration: 900000